In [1]:
# Bart Post-COVID Recovery Analysis

#**Question** Which BART stations recovered to pre-pandemic ridership levels, if at all? 

# **Data:** BART monthly origin-destination matrices, 2018–2025, 
# downloaded from bart.gov. Each file contains four tabs (Total Trips, 
# Average Weekday, Average Saturday, Average Sunday) and is structured 
# as a wide matrix with origin stations across columns and destination 
# stations down rows.


# **Notebook 1 of N:** Initial data exploration — understanding what 
# BART actually publishes before doing any analysis.

In [2]:
import pandas as pd
import os

data_path = '../Data/raw'
print(os.listdir(data_path))

#rename
for folder_name in os.listdir(data_path):
    if folder_name == '.DS_Store':
        continue
    
    full_path = os.path.join(data_path, folder_name)
    if not os.path.isdir(full_path):
        continue
    
    new_name = folder_name.lower().replace(' ', '_')
    
    if new_name != folder_name:
        old_path = os.path.join(data_path, folder_name)
        new_path = os.path.join(data_path, new_name)
        os.rename(old_path, new_path)
        print(f"renamed: '{folder_name}'  →  '{new_name}'")

['.DS_Store', 'ridership_2018', 'ridership_2020', 'ridership_2021', 'ridership_2019', 'ridership_2023', 'ridership_2024', 'ridership_2025', 'ridership_2022', 'bart_abbs.xls']

In [3]:
#rename
for folder_name in os.listdir(data_path):
    if folder_name == '.DS_Store':
        continue
    
    full_path = os.path.join(data_path, folder_name)
    if not os.path.isdir(full_path):
        continue
    
    new_name = folder_name.lower().replace(' ', '_')
    
    if new_name != folder_name:
        old_path = os.path.join(data_path, folder_name)
        new_path = os.path.join(data_path, new_name)
        os.rename(old_path, new_path)
        print(f"renamed: '{folder_name}'  →  '{new_name}'")

In [4]:
year_2024_p = '../Data/raw/ridership_2024'

for folder_name in sorted(os.listdir(year_2024_p)):
    if folder_name != '.DS_Store':
        print(folder_name)

Ridership_202401.xlsx
Ridership_202402.xlsx
Ridership_202403.xlsx
Ridership_202404.xlsx
Ridership_202405.xlsx
Ridership_202406.xlsx
Ridership_202407.xlsx
Ridership_202408.xlsx
Ridership_202409.xlsx
Ridership_202410.xlsx
Ridership_202411.xlsx
Ridership_202412.xlsx

In [5]:
import pandas as pd

file_path = os.path.join(year_2024_p, 'Ridership_202401.xlsx')

xl = pd.ExcelFile(file_path)

print(xl.sheet_names)

['Total Trips', 'Average Weekday', 'Average Saturday', 'Average Sunday']

In [6]:
# Step 3: Open the Average Weekday tab

# For recovery analysis, I'll focus on **Average Weekday** ridership 
# since that's the metric most affected by post-COVID work-from-home 
# patterns. Weekend ridership tells a different story.

# Each tab is structured as a wide origin-destination matrix with 
# origin stations across the columns and destination stations down 
# the rows. Each cell is the average number of trips between those 
# two stations on a typical weekday that month.

In [7]:
weekday_jan_2024 = pd.read_excel(file_path, sheet_name = 'Average Weekday')
weekday_jan_2024.head()

,Avg Weekday Trip OD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024 / 01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,...,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday
3,Exit Station Two-Letter Code,RM,EN,EP,NB,BK,AS,MA,19,12,...,SO,MB,WD,OA,WS,PC,AN,ML,BE,NaN
4,RM,12.428571,69.666667,58.428571,33.571429,222.714286,47.095238,75.761905,62.190476,76.142857,...,35.857143,11.47619,4.190476,7.809524,13.333333,3.952381,10.47619,5.238095,6,2054.857143

In [8]:
weekday_jan_2024 = pd.read_excel(file_path, sheet_name = 'Average Weekday')
weekday_jan_2024.head()

,Avg Weekday Trip OD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024 / 01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,...,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday,Avg Weekday
3,Exit Station Two-Letter Code,RM,EN,EP,NB,BK,AS,MA,19,12,...,SO,MB,WD,OA,WS,PC,AN,ML,BE,NaN
4,RM,12.428571,69.666667,58.428571,33.571429,222.714286,47.095238,75.761905,62.190476,76.142857,...,35.857143,11.47619,4.190476,7.809524,13.333333,3.952381,10.47619,5.238095,6,2054.857143

In [9]:
weekday_jan_2024 = pd.read_excel(file_path,skiprows=4)
print(weekday_jan_2024)

   Exit Station Two-Letter Code     RM     EN     EP     NB      BK     AS  \
0                            RM    425   1800   1556    870    5754   1216
1                            EN   1822    545   1712   1258    9138   1528
2                            EP   1651   1528    219    884    7677   1167
3                            NB    884   1056    878    266    2015    648
4                            BK   6545   9449   7961   2310    1083   3814
5                            AS   1189   1484   1260    815    3710    297
6                            MA   2306   2615   1423    987    3854   1073
7                            19   1700   3598   2307   2055    5049   2138
8                            12   1993   4282   2526   1897    5024   2019
9                            LM    521    920    629    498    2225    636
10                           FV   1358   1586    679    753    3026   1362
11                           CL   1054    872    247    338    1375    506
12                           SL    614    860    369    476    1788    574
13                           BF    304    438    282    243    1353    344
14                           HY    402    711    232    293    1253    362
15                           SH    225    258    115     86     890    176
16                           UC    169    440    209    154    1572    214
17                           FM    239    455    194    235    1403    278
18                           CN    338    406    201    244    1109    229
19                           PH    162    257    248    170    1075    266
20                           WC    385    416    301    357    1394    276
21                           LF    228    195    140    120     593    137
22                           OR    161    161    121     90     385     63
23                           RR    395    477    421    240     465    197
24                           OW    527    451    126    325     986    433
25                           EM   5037   9726   6223   7162   10268   6643
26                           MT   4926   8516   5171   5517    7889   5793
27                           PL   5485   8750   3706   3320    7426   3723
28                           CC   3715   6234   3210   3699    5272   4367
29                           16   2310   2887   1137   1774    3275   2171
30                           24   2431   2261    960   1154    2883   1333
31                           GP    608    860    384    468    1583    409
32                           BP    885   1057    342    358     925    407
33                           DC    785   1250    415    250    1034    276
34                           CM    287    293     88    102     371     85
35                           CV     91    120     67     37     389     80
36                           ED    159    258    143    140    1010    191
37                           NC     57     42     68     28     207     20
38                           WP    287    201     71     81     706    105
39                           SS    242    424     91     71     402     92
40                           SB    307    369    138     71     421    139
41                           SO    930   1263    755   1175    1948    702
42                           MB    341    661    227    256    1218    290
43                           WD    107    203     85     38     381     94
44                           OA    176    357    277    322     602    220
45                           WS    355    478    131    175     587    181
46                           PC    109     71     27     18     182     53
47                           AN    218    258     59     60     491    124
48                           ML    199    372    198    218    1380    284
49                           BE    217    449    185    252    1913    360
50                  Grand Total  55861  82620  48514  42710  116959  48095

       MA      19      12  ...     SO     MB     WD     OA     WS     PC  \
0    1971    1521    1881  ...   1043    294    101    215    318    100
1    2711    3441    4608  ...   1550    763    186    533    505     71
2    1620    2357    2636  ...    988    247     93    372    135     16
3    1041    1966    1865  ...   1513    255     32    464    171     18
4    3845    5462    5642  ...   4509   1233    339   1787    602    198
5     982    2006    2147  ...   1174    252     53    370    182     67
6     554    2221    2587  ...   1621    419    228    388    516    419
7    2290     568     552  ...   1426    710    501    470    758    292
8    2478     543     662  ...   1954    876    421    494    660    280
9     680     349     339  ...    406    139   1217    392    979     88
10   2302    1623    1641  ...    842    223    895    210    953    127
11   1462    1242    1570  ...    270    229    251    341    785    149
12   1452    1940    2972  ...    452     90    760    155   1198     57
13    926    1390    2168  ...    379    134    937    115   1103     78
14    860    1393    1920  ...    225    132    499    151   1600     82
15    552     729    1164  ...    117     53    355    132   1393     25
16    670    1323    1941  ...    311     66    382    224   1531     37
17    667    1286    1538  ...    475     42    302    277   1604     69
18   1837    1781    2078  ...   1465    234     95    371    103   1366
19   1453    1859    2547  ...   1894    134     26    472    101    444
20   1778    2379    2585  ...   2266    244     17    439     54    676
21    740    1302    1149  ...   1353     62      4    227     64    141
22    473     883    1048  ...    973     43     14    139     22    140
23   1034    2141    1922  ...   2148    139     58    230    110    223
24    819    1004    1263  ...   1675    333    134    132    141    112
25  10944   15067   14923  ...   4880   4581   6446   1433   2088    707
26   9102   11317   10671  ...   4925   5435   3991   1045   1786    741
27   6981    8197    9946  ...  14173   4268   2243   1108   1091   1010
28   7243    7969    6955  ...   5329   3846   1734    589    899    656
29   4340    4780    4106  ...   3856   2354    659    342    440    364
30   2802    3227    3104  ...   2720   2019    392    313    215    174
31    964    1589    1610  ...   1886   1161    186    216     99     51
32    885    1134    1572  ...   1624   1422    281    133    129    135
33    839    1140    1537  ...   3518   2792    289    190    153    169
34    163     355     628  ...   1536   1042     25     21     25     78
35    192     363     351  ...    196     64   1191     88    187      6
36    589    1126    1791  ...   1785    166    437    907    308      9
37    345     426     719  ...    494     33      4    123     51    302
38   1608     975    1753  ...   1445    198     14    261    101    151
39    208     513     784  ...    918    632     57     44     47     23
40    326     581     749  ...   1993    465     44     34     34     64
41   1248    1037    1461  ...   1590   4823    329    326    142    167
42    440     609     899  ...   8256    755     45     93     17     20
43    271     536     535  ...    481     50    206    325    154     15
44    245     271     438  ...    332     31    233    135     61     30
45    580     819     705  ...    216      6    128    109    204     71
46    369     321     283  ...    173     24     22     38     39     42
47   1283    1096    1589  ...   1208    230     16    281    158    423
48    409     782     761  ...    251      6    213    167   1715     13
49    698     828     941  ...    218     12    309    186   1782     25
50  88271  107767  119236  ...  95032  43761  27394  17607  27513  10721

       AN     ML     BE  Unnamed: 51
0     251    165    189        52671
1     236    377    451        86380
2      90    205    211        49372
3      62    195    240        41330
4     473   1404   1826       124864
5     131    300    315        46692
6    1359    426    639        86245
7    1193    759    803       104869
8    1621    715    918       113650
9     327    686    735        67970
10    300    751    883        88798
11    543    452    463        45380
12    390    876    735        73473
13    114    681    545        58721
14    279   1341   1154        48778
15     91    769    749        30963
16     73   1483   1305        41263
17    137   2067   1805        45027
18   1989    204    173        56699
19    866    124    136        53452
20   1533    157    116        63442
21    249     32     48        35751
22    145     42     40        27410
23    589    122    142        59764
24    264    140    124        83493
25   5239   3142   3449       371066
26   4227   2560   2741       318230
27   3525   1601   1779       281823
28   3475   1230   1314       209248
29   1319    414    553       138616
30    895    308    358       133728
31    572    130    134        75419
32    467    145    161        93017
33    525    285    262        99982
34    265     15     21        34314
35     51    116    124        26952
36     71    512    660        66241
37    309     17     47        13269
38    496     81     76        45180
39    287     40     11        31830
40    258     19     12        35240
41   1029    131     87        68288
42    177     10      9        44487
43     24    212    276        28211
44    193    124     94        11986
45    167   1567   1530        26201
46    504     16     21        10610
47    375     91    112        35598
48     94    475    488        27860
49    123    497    356        30790
50  37972  28211  29420      3844643

[51 rows x 52 columns]

In [10]:
!pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.13/site-packages (2.0.2)

In [11]:
stations_p = "../Data/raw/bart_abbs.xls"
stations = pd.read_excel(stations_p, usecols=['Two-Letter Station Code', 'Station Name'])
stations.head()

stations

   Two-Letter Station Code                         Station Name
0                       RM                             Richmond
1                       EN                 El Cerrito Del Norte
2                       EP                     El Cerrito Plaza
3                       NB                       North Berkeley
4                       BK                             Berkeley
5                       AS                                Ashby
6                       MA                            MacArthur
7                       19                  19th Street Oakland
8                       12    12th Street / Oakland City Center
9                       LM                         Lake Merritt
10                      FV                            Fruitvale
11                      CL                             Coliseum
12                      SL                          San Leandro
13                      BF                              Bayfair
14                      HY                              Hayward
15                      SH                        South Hayward
16                      UC                           Union City
17                      FM                              Fremont
18                      CN                              Concord
19                      PH                        Pleasant Hill
20                      WC                         Walnut Creek
21                      LF                            Lafayette
22                      OR                               Orinda
23                      RR                            Rockridge
24                      OW                         West Oakland
25                      EM                          Embarcadero
26                      MT                    Montgomery Street
27                      PL                        Powell Street
28                      CC                         Civic Center
29                      16                  16th Street Mission
30                      24                  24th Street Mission
31                      GP                            Glen Park
32                      BP                          Balboa Park
33                      DC                            Daly City
34                      CM                                Colma
35                      CV                        Castro Valley
36                      ED                    Dublin/Pleasanton
37                      NC                        North Concord
38                      WP                  Pittsburg/Bay Point
39                      SS                  South San Francisco
40                      SB                            San Bruno
41                      SO  San Francisco International Airport
42                      MB                             Millbrae
43                      WD               West Dublin/Pleasanton
44                      OA        Oakland International Airport
45                      WS                         Warm Springs
46                      AN                              Antioch
47                      PC                     Pittsburg Center
48                      ML                             Milpitas
49                      BE           Berryessa / North San José